version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        while ! nc -z $MYSQL_HOST 3306; do  # Используем переменную Railway
          sleep 1
        done &&
        echo 'Database is ready!' &&
        python manage.py makemigrations main &&
        until python manage.py migrate; do
          echo 'Migration failed, retrying in 3s...'
          sleep 3
        done &&
        python manage.py runserver 0.0.0.0:$$PORT
      "
    ports:
      - "$$PORT:8000"
    environment:
      MYSQL_HOST: $MYSQL_HOST          # Берётся из Railway MySQL add-on
      MYSQL_USER: $MYSQL_USER          # Берётся из Railway MySQL add-on
      MYSQL_PASSWORD: $MYSQL_PASSWORD  # Берётся из Railway MySQL add-on
      MYSQL_DATABASE: $MYSQL_DATABASE  # Берётся из Railway MySQL add-on
      PORT: 8000